/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportStationIdRouteImport } from './routes/report.$stationId'
import { Route as ECodeRouteImport } from './routes/e.$code'

const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportStationIdRoute = ReportStationIdRouteImport.update({
  id: '/report/$stationId',
  path: '/report/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ECodeRoute = ECodeRouteImport.update({
  id: '/e/$code',
  path: '/e/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manager': typeof ManagerRoute
  '/e/$code': typeof ECodeRoute
  '/report/$stationId': typeof ReportStationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manager': typeof ManagerRoute
  '/e/$code': typeof ECodeRoute
  '/report/$stationId': typeof ReportStationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manager': typeof ManagerRoute
  '/e/$code': typeof ECodeRoute
  '/report/$stationId': typeof ReportStationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manager' | '/e/$code' | '/report/$stationId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manager' | '/e/$code' | '/report/$stationId'
  id: '__root__' | '/' | '/manager' | '/e/$code' | '/report/$stationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManagerRoute: typeof ManagerRoute
  ECodeRoute: typeof ECodeRoute
  ReportStationIdRoute: typeof ReportStationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$stationId': {
      id: '/report/$stationId'
      path: '/report/$stationId'
      fullPath: '/report/$stationId'
      preLoaderRoute: typeof ReportStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$code': {
      id: '/e/$code'
      path: '/e/$code'
      fullPath: '/e/$code'
      preLoaderRoute: typeof ECodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManagerRoute: ManagerRoute,
  ECodeRoute: ECodeRoute,
  ReportStationIdRoute: ReportStationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
